name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 8884691005/myaddressbooK
    - name: Docker credentials
      run: docker login --username 8884691005 --password ${secret.DOCKER_SECRET}  
    - name: Pushing the image on DockerHub
      run: docker push 8884691005/myaddressbook
