name: "Sync GHAS to Jira"

on:
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes
  workflow_dispatch:
    

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://devtoolsindia.atlassian.net/'
          jira_user: 'tejaswinid@devtools.in'
          jira_token: '6SMETXbw1hFFwKlEYBND9ED5'
          jira_project: 'DE'
          github_token: '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'
          sync_direction: 'gh2jira'
